---
server: true
markdown: maruku
auto: true
permalink: /blog/:year-:month-:day-:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true
# paginate: 20
title : "OpenHackVE"
tagline: Tagline
author :
  name : Neftalí Yagua
  email : openhackve@groups.google.com
  github : neftaliyagua
  twitter : NeftaliYagua
# RSS
name: Desarrollador Neftalí Yagua
title: Desarrollador Neftalí Yagua
url: https://dev.neftaliyagua.com.ve
production_url : https://dev.neftaliyagua.com.ve
JB :
  version : 0.3.0
  BASE_PATH : false
  ASSET_PATH : false
  archive_path: /archivo.html
  categories_path : /categorias.html
  tags_path : /tags.html
  comments :
    provider : false
  sharing :
    provider : false
cities:
- caracas:
    name: Caracas, Distrito Capital
    latitude: 10.517578
    longitude: -66.916666
- valencia:
    name: Valencia, Carabobo
    latitude: 10.180457
    longitude: -67.999878
- san_felipe:
    name: San Felipe, Yaracuy
    latitude: 10.340557
    longitude: -68.736949
- cocorote:
    name: Cocorote, Yaracuy
    latitude: 10.322498
    longitude: -68.783051
- porlamar:
    name: Porlamar, Nueva Esparta
    latitude: 10.960468
    longitude: -63.850586

- El_Tigre:
    name: El Tigre, Anzoàtegui
    latitude: 8.38333
    longitude: -65.15

- San_Jose_de_guanipa:
    name: San Josè de Guanipa, Anzoàtegui
    latitude:  8.89333
    longitude: -64.15917
