---
server: true
markdown: maruku
auto: true
permalink: /:categories/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true
markdown: rdiscount
# paginate: 20
title : "OpenHackVE"
tagline: Tagline
author :
  name : OpenHack Team
  email : openhackve@groups.google.com
  github : OpenHackVE
  twitter : OpenHackVE

# RSS
name: OpenHackVE
url: http://openhackve.github.io

production_url : http://openhackve.github.io

JB :
  version : 0.2.13
  BASE_PATH : false
  ASSET_PATH : false
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  comments :
    provider : disqus
    disqus :
      short_name : elblogdeabr4xas
    livefyre :
      site_id : 123
    intensedebate :
      account : 123abc
    facebook :
      appid : 123
      num_posts: 5
      width: 580
      colorscheme: light
cities:
- caracas:
    name: Caracas, Distrito Capital
    latitude: 10.517578
    longitude: -66.916666
- valencia:
    name: Valencia, Carabobo
    latitude: 10.180457
    longitude: -67.999878
- san_felipe:
    name: San Felipe, Yaracuy
    latitude: 10.340557
    longitude: -68.736949
- cocorote:
    name: Cocorote, Yaracuy
    latitude: 10.322498
    longitude: -68.783051
- porlamar:
    name: Porlamar, Nueva Esparta
    latitude: 10.960468
    longitude: -63.850586