---
server: true
markdown: maruku
auto: true
cities:
- caracas:
    name: Caracas, Distrito Capital
    latitude: 10.517578
    longitude: -66.916666
- valencia:
    name: Valencia, Carabobo
    latitude: 10.180457
    longitude: -67.999878